### ISSUE TITLE
SDK (V4.20) doesn't work with Turbopack in NextJS after updating to V15.2.1

### ISSUE THREAD

**Issue by SouthCentralCode** [RetellAI/retell-typescript-sdk#275]
The following code (running in a nextjs route (route.ts)): 

`const retellClient = new RetellClient({apiKey: process.env.RETELL_API_KEY as string});`
`const voiceOptions = await retellClient.voice.list();`

Triggers this runtime error :

`TypeError: (0 , __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f2e$pnpm$2f$retell$2d$sdk$40$4$2e$19$2e$0$2f$node_modules$2f$retell$2d$sdk$2f$_shims$2f$registry$2e$mjs__$5b$app$2d$route$5d$__$28$ecmascript$29$__.getDefaultAgent) is not a function
web:dev:     at Retell.buildRequest (src/core.ts:297:77)
web:dev:     at Retell.makeRequest (src/core.ts:430:39)`

I can recreate this issue on demand by switching between versions.

Downgrading to  "next": "15.1.7" fixes the issue and the voices return as expected.I know the V15.2.1 includes a lot of turbopack related updates.

* Using pnpm.

**Comment by dgellow** [comment]
Hi @SouthCentralCode, that should be fixed since [v4.23.0](https://github.com/RetellAI/retell-typescript-sdk/pull/287). Could you give it a try and confirm?

**Comment by fedorkar** [comment]
This Turbopack compatibility issue was fixed in v4.23.0 through #287, and the fix is included in current releases. Since there has been no further report after the fix was provided, closing this as completed. If the issue still occurs with the current SDK and Next.js, please open a new issue with a minimal reproduction and the exact versions involved.
